import typer
import re
import subprocess
from pathlib import Path
from datetime import datetime
from rich.console import Console
from rich.panel import Panel
from rich.text import Text
from rich.table import Table
from rich import box

# Setup
app = typer.Typer(no_args_is_help=True)
console = Console()
PROGRESS_FILE = Path("PROGRESS.md")

def get_content():
    if not PROGRESS_FILE.exists():
        console.print("[bold red]❌ Error:[/bold red] PROGRESS.md not found.")
        raise typer.Exit(code=1)
    return PROGRESS_FILE.read_text(encoding="utf-8")

def parse_progress(content):
    phase_match = re.search(r"\* \*\*Phase:\*\* (.*)", content)
    task_match = re.search(r"\* \*\*Current Task:\*\* (.*)", content)
    phase = phase_match.group(1).strip() if phase_match else "Unknown"
    task = task_match.group(1).strip() if task_match else "Unknown"
    return phase, task

# --- COMMAND 1: STATUS ---
@app.command()
def status():
    """Zeigt den aktuellen Status an."""
    content = get_content()
    phase, task = parse_progress(content)

    status_content = Text()
    status_content.append("\n📍 Current Phase:\n", style="bold white")
    status_content.append(f"   {phase}\n", style="yellow")
    status_content.append("\n🔨 Current Task:\n", style="bold white")
    status_content.append(f"   {task}\n", style="cyan")

    console.print(Panel(
        status_content, 
        title="[bold green]Antigravity System Status[/bold green]",
        expand=False,
        border_style="green"
    ))

# --- COMMAND 2: START ---
@app.command()
def start(task_name: str):
    """Startet Task: Updated Markdown."""
    content = get_content()
    pattern = r"(\* \*\*Current Task:\*\* )(.*)"
    
    if not re.search(pattern, content):
        console.print("[bold red]❌ Error:[/bold red] 'Current Task' line missing.")
        raise typer.Exit(code=1)

    new_content = re.sub(pattern, f"\\1{task_name}", content)
    PROGRESS_FILE.write_text(new_content, encoding="utf-8")

    console.print(f"[bold green]🚀 Started Task:[/bold green] {task_name}")

# --- COMMAND 3: FINISH ---
@app.command()
def finish():
    """Beendet Task -> Loggt in Markdown -> Git Commit."""
    content = get_content()
    
    task_match = re.search(r"\* \*\*Current Task:\*\* (.*)", content)
    current_task = task_match.group(1).strip() if task_match else "Unknown"

    if current_task in ["Unknown", "Waiting for input", ""]:
        console.print("[yellow]⚠️  No active task to finish.[/yellow]")
        raise typer.Exit()

    # Reset Task & Write Log
    new_content = re.sub(r"(\* \*\*Current Task:\*\* )(.*)", r"\1Waiting for input", content)
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    # Format: * **TIMESTAMP:** MESSAGE
    log_entry = f"\n* **{timestamp}:** {current_task}"
    
    if "## Changelog" in new_content:
        new_content = new_content.replace("## Changelog", f"## Changelog{log_entry}")
    else:
        new_content += log_entry

    PROGRESS_FILE.write_text(new_content, encoding="utf-8")
    console.print(f"[dim]📝 Logged to PROGRESS.md[/dim]")

    try:
        console.print("[bold blue]💾 Committing to Git...[/bold blue]")
        subprocess.run(["git", "add", "."], check=True)
        subprocess.run(["git", "commit", "-m", f"Finish: {current_task}"], check=True)
        console.print(f"[bold green]✅ Success![/bold green] Task archived.")
    except Exception as e:
        console.print(f"[red]Git Error: {e}[/red]")

# --- COMMAND 4: LOG (NEU) ---
@app.command()
def log(markdown: bool = False, export: bool = False):
    """
    Zeigt die Historie an.
    Optionen:
    --markdown: Gibt rohes Markdown aus (gut für Pipes).
    --export: Speichert die Historie in HISTORY.md.
    """
    content = get_content()
    
    # Wir suchen nach dem Changelog Abschnitt
    if "## Changelog" not in content:
        console.print("[yellow]No changelog found yet.[/yellow]")
        return

    # Alles nach "## Changelog" nehmen
    changelog_raw = content.split("## Changelog")[1].strip()
    lines = changelog_raw.split("\n")
    
    entries = []
    # Regex um Timestamp und Nachricht zu trennen
    # Format aus finish(): * **YYYY-MM-DD HH:MM:** Task Name
    pattern = r"\* \*\*(.*?):\*\* (.*)"
    
    for line in lines:
        match = re.search(pattern, line)
        if match:
            entries.append({"time": match.group(1), "task": match.group(2)})

    if not entries:
        console.print("[dim]Changelog is empty.[/dim]")
        return

    # MODUS A: EXPORT (File)
    if export:
        history_file = Path("HISTORY.md")
        md_content = "# Project History\n\nGenerated by Antigravity CLI\n\n"
        md_content += "| Timestamp | Task Completed |\n"
        md_content += "|-----------|----------------|\n"
        for entry in entries:
            md_content += f"| {entry['time']} | {entry['task']} |\n"
        
        history_file.write_text(md_content, encoding="utf-8")
        console.print(f"[bold green]✅ Exported to {history_file.name}[/bold green]")
        return

    # MODUS B: RAW MARKDOWN (Stdout)
    if markdown:
        for entry in entries:
            print(f"- **{entry['time']}**: {entry['task']}")
        return

    # MODUS C: PRETTY TABLE (Default)
    table = Table(title="Antigravity Project Log", box=box.ROUNDED)
    table.add_column("Timestamp", style="cyan", no_wrap=True)
    table.add_column("Completed Task", style="white")

    for entry in entries:
        table.add_row(entry['time'], entry['task'])

    console.print(table)

if __name__ == "__main__":
    app()